# -*- coding: utf-8 -*-
"""PROBABILITY_PROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K3LKyWySCgrC7x74AJpexijXXkICtut8

# **Sales of Cars Comparator**
## *Made By:*
## *Utkarsh Vijayvergia(E20CSE177)*
## *Kshitij Gupta(E20CSE163)*
## *Tanishq Agarwal(E20CSE175)* 

---
## This model will help the user in identifying the selling trends of cars of different companies during the range of 1983 to 2020.
We have picked up up an database of sales of car names Cars details v3.csv.
After cleaning we solved the following problems with it➡


1.   Sales of cars wrt type of fuel.
2.   Sales of cars wrt Car Companies.
3.   Sales of cars wrt type of transmission.
4.   Mileage Comparison of cars wrt to Car Companies.
5.   Comparison of Total Cars and Cars that can be used legally today    of    Companies Hyundai and Maruti.

First of all,we need to import numpy, pandas, seeborn, matplotlib and datetime libraries in our project.
1. NumPy is a Python library that provides a simple yet powerful data structure: the n-dimensional array. This is the foundation on which almost all the power of Python's data science toolkit is built.
2. Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.
3. Seaborn is a Python data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical.
4. Matplotlib is a low-level plotting library and is one of the most widely used plotting libraries. It is among the first choices to plot graphs for quickly visualizing some data.
5. In Python, date and time are not a data type of their own, but a module named datetime can be imported to work with the date as well as time.
"""

#importing all libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import date
from matplotlib.pyplot import figure

df=pd.read_csv("/content/Car details v3.csv")

"""Then we will be reading our csv file ***Car details v3.csv***.

This is our original raw data.
"""

df

"""Heat Chart of raw data made using matplotlib library."""

plt.subplots(figsize=(5,5))# for setting figure size.
sns_plot = sns.heatmap(df.corr(),annot =True,cmap='rainbow_r',square=True)#plotting heatmap
fig = sns_plot.get_figure()#these two lines are for saving this image.
fig.savefig("corrHeatmap.png")

"""## Data Cleaning

---



---



---


Now we will begin with our data cleaning. We will..
1. Delete torque field as we don't need it.
2. Add column **Age** for age of each car.
3. Add column **company** for grouping of cars.
4. Add column **mileage_int** to save float value of mileage.

"""

del df["torque"]# deleting column torque

date=date.today()#finding todays date using datetime library.
tod=date.year
df["Age"]=tod-df["year"]#setting values of Age.
df

def getname(x):#Function to recieve name of Company
  return x.split()[0]#returning name of Company
k=0
df["company"]=""
for i in df["name"]:
  df["company"][k]=getname(i)#setting values for company
  k+=1
df

def getname(x):#function for extracting mileage from mileage column
  return x.split()[0]
k=0
df["mileage_int"]=""
for i in df["mileage"]:
  if(type(i)==str):
    df["mileage_int"][k]=getname(i)#Setting value of mileage_int using mileage.
  k+=1
df

plt.figure(figsize=(11,9))
sns.pairplot(df,hue = 'fuel')
plt.show()

"""# Task-1
## Sales of Cars wrt to fuel


---
In this task we will check that among fuels of cars whose kind is most abundant.
With this we can find the trends of when the cars of particular fuel type was sold the most.



"""

df=df.sort_values("year")#sorting table by year
xi=df.year.unique()#unique years
x=[]
y=[]
z=[]
a=[]
df
for i in xi:#for each year.
  x.append(len(df[(df.fuel=="Diesel") & (df.year==i)]))#Diesel count that year
  y.append(len(df[(df.fuel=="Petrol") & (df.year==i)]))#Petrol count that year
  z.append(len(df[(df.fuel=="LPG") & (df.year==i)]))#LPG count that year
  a.append(len(df[(df.fuel=="CNG") & (df.year==i)]))#CNG count that year
m=df.fuel.unique()#unique fuel.
sns.set(rc = {'figure.figsize':(10,8)})
plt.plot(xi,x,color='green',linestyle='solid',linewidth=2,marker="D",markerfacecolor='yellow')#line chart for Diesel
plt.plot(xi,y,color='red',linestyle='solid',linewidth=2,marker="D",markerfacecolor='yellow')#line chart for Petrol
plt.plot(xi,z,color='blue',linestyle='solid',linewidth=2,marker="D",markerfacecolor='yellow')#line chart for LPG
plt.plot(xi,a,color='brown',linestyle='solid',linewidth=2,marker="D",markerfacecolor='yellow')#line chart for CNG
plt.legend(labels=df.fuel.unique(),fontsize=20)

"""From the above line chart we can infer that..
1. The trend of selling of cng and lpg fuel type cars have remained almost constant through out the years.
2. Though starting of each type was from zero, selling of Petrol and Diesel fuel type cars climbed by leaps and bounds since 2010 and reaching all time peak by 2016 and then again reduced.
3. The reason of leap was due to low prices of Diesel, most people started buying diesel driven vehicles.
4. Through research we found that in **Auto Expo 2016 popularised "hard selling diesel cars"; avoiding health risks: CSE**. During this expo, it was found that most cars in exhibitions run on diesel which causes a lot of pollution compared to Petrol vehicles. link->https://auto.economictimes.indiatimes.com/news/industry/auto-expo-2016-popularised-hard-selling-diesel-cars-avoiding-health-risks-cse/50936818
Due to this and some similar events, the sales of Diesel cars decreased.

# Task-2
## Sales of Car wrt Car Companies.
---
In this task, we will find which company's cars were sold the most.
With this we can also infer the development of Car Companies between 1983 to 2020.
"""

xi=df.company.unique()# to find unique cars.
yi=[]
for i in xi:
  yi.append(len(df[df['company']==i]))#count each companies car.
sns.set(rc = {'figure.figsize':(45,20)})
e=sns.barplot(x=xi,y=yi,data=df)
e.set_xlabel("company")
e.set_ylabel("")
e.legend(labels=df.company.unique(),fontsize=20)

"""From the above graph we can infer Maruti and Hyundai cars were sold the most. It is so as Maruti cars and their spare parts are much cheaper than other cars.
Hyundai are sold the most because of their better quality and efficient cars.

# Task-3
## Sales of car wrt to Transmission
---
In this task we will find which type of cars Indian usually prefer while buying.
"""

xi=df.company.unique()#finding unique companies in dataset
y1=[]
y2=[]
for i in xi:
  df1=df[(df.company==i) & (df.transmission=="Manual")]#count of manual cars
  df2=df[(df.company==i) & (df.transmission=="Automatic")]# count of automatic cars
  y1.append(len(df1))
  y2.append(len(df2))
sns.set(rc = {'figure.figsize':(40,10)})#chart size
plt.plot(xi,y1,color='green',linestyle='solid',linewidth=2,marker="D",markerfacecolor='red')#green line of Manual
plt.plot(xi,y2,color='blue',linestyle='solid',linewidth=2,marker="D",markerfacecolor='red')#blue line of automatic
plt.legend(labels=df.transmission.unique(),fontsize=30)

"""We found from graph that mostly automatic cars of BMW, Honda, Maruti, Hyundai and Jaguar are sold the most.
Manual cars have more edge over automatic cars leading over by Maruti, Hyundai and Tata.
**Thus we can say that Indians usually prefer manual cars over automatic cars**.

# Task-4
## Mileage Comparison of Cars wrt Car Companies
---
In this task, we will compare the  mileages of Cars of each Company in dataset and find which companies average mileage is best.
"""

xi=df.company.unique()#finding unique companies.
yi=[]
for i in range(int(len(xi)/2)):#since it is large chart we will make two charts, this is the first chart
  m1=[]
  for j in range(len(df[df['company']==xi[i]])):
    if(df['mileage_int'][j]!=""):
      m1.append(float(df['mileage_int'][j]))
  yi.append(np.mean(m1))#finding mean using numpy
sns.set(rc = {'figure.figsize':(15,10)})
e=sns.barplot(x=xi[:int(len(xi)/2)],y=yi,data=df)#window size
e.set_xlabel("Company")
e.set_ylabel("Mileage")
ticks=[0,5.0,10.0,15.0,20.0,25.0,30.0]#ticks on y-axis
e.set_yticks(ticks)#setting y-axis
e.set_yticklabels(ticks)#y-axis labels
e.legend(labels=xi[:int(len(xi)/2)],fontsize=15,bbox_to_anchor=(1.0, 1.15))#legends

xi=df.company.unique()#finding unique companies.
yi=[]
for i in range(int(len(xi)/2),int(len(xi))):#since it is large chart we will make two charts, this is the second chart
  m1=[]
  for j in range(len(df[df['company']==xi[i]])):
    if(df['mileage_int'][j]!=""):
      m1.append(float(df['mileage_int'][j]))
  yi.append(np.mean(m1))#finding mean using numpy
sns.set(rc = {'figure.figsize':(15,10)})
e=sns.barplot(x=xi[int(len(xi)/2):],y=yi,data=df)
e.set_xlabel("Company")
e.set_ylabel("Mileage")
ticks=[0,5.0,10.0,15.0,20.0,25.0,30.0]
e.set_yticks(ticks)
e.set_yticklabels(ticks)
e.legend(labels=xi[int(len(xi)/2):],fontsize=15,bbox_to_anchor=(1.0, 1.15))

"""We have also made a line chart to make it more clear."""

xi=df.company.unique()
yi=[]
for i in range(int(len(xi))):
  m1=[]
  for j in range(len(df[df['company']==xi[i]])):
    if(df['mileage_int'][j]!=""):
      m1.append(float(df['mileage_int'][j]))
  yi.append(np.mean(m1))
sns.set(rc = {'figure.figsize':(45,10)})
plt.plot(xi,yi,color='green',linestyle='solid',linewidth=2,marker="D",markerfacecolor='red')

"""From the above bar graph and line chart, we can find the best mileage is given by Ashok, Opel, Peugeot. So if we want to consider cars with better mileage, this should be our first preference.

# Task-5
## Comparison of Total Cars and Cars that can be used legally today of Companies Hyundai and Maruti.
---
As Hyundai and Maruti has most cars we will be checking how many of these car can we use under government's laws. For Diesel vehicles, age of car must be less than 10 and for petrol car it should be less than 15.

For Petrol Cars
"""

xi=['Hyundai','Maruti']#cars we are taking.
yi=[]
yi.append(len(df[df['company']=="Hyundai"]))
yi.append(len(df[df['company']=="Maruti"]))
zi=[]
df1=df[(df.company=='Hyundai') & (df.Age<15) & (df.fuel=="Petrol")]#cars under our condition of Hyundai
df2=df[(df.company=='Maruti') & (df.Age<15)& (df.fuel=="Petrol")]#cars under our condition of Maruti
zi.append(len(df1))
zi.append(len(df2))
sns.set(rc = {'figure.figsize':(5,5)})#figure size

df1=pd.DataFrame({'Company':xi,'No. of Cars':yi})
df2=pd.DataFrame({'Company':xi,'No. of Cars':zi})
df1['Variation']="Total Cars"
df2['Variation']="Legal Cars"
res=pd.concat([df1,df2])#for displaying together 
sns.barplot(x='Company',y='No. of Cars',data=res,hue='Variation',palette="rocket")#bar plot
plt.show()

"""Now for Diesel Cars"""

xi=['Hyundai','Maruti']#cars we are taking.
yi=[]
yi.append(len(df[df['company']=="Hyundai"]))
yi.append(len(df[df['company']=="Maruti"]))
zi=[]
df1=df[(df.company=='Hyundai') & (df.Age<10) & (df.fuel=="Diesel")]#cars under our condition of Hyundai
df2=df[(df.company=='Maruti') & (df.Age<10)& (df.fuel=="Diesel")]#cars under our condition of Maruti
zi.append(len(df1))
zi.append(len(df2))
sns.set(rc = {'figure.figsize':(5,5)})#figure size

df1=pd.DataFrame({'Company':xi,'No. of Cars':yi})
df2=pd.DataFrame({'Company':xi,'No. of Cars':zi})
df1['Variation']="Total Cars"
df2['Variation']="Legal Cars"
res=pd.concat([df1,df2])#for displaying together 
sns.barplot(x='Company',y='No. of Cars',data=res,hue='Variation',palette="rocket")#bar plot
plt.show()

"""From the above two bar graphs we can infer that although Hyundai and Maruti has most cars, their legal cars sold are less than 50%. So we must be careful while parchasing these cars or else we will face trouble in some states.

# **SUMMARY**
1. Task-1--- We found about how much the car of different types of fuel are sold and why.
2. Task-2--- We found which company's car sold the most and why.
3. Task-3--- We found that Indian prefer Manual cars more than Automatic cars.
4. Task-4--- We found which Company normally sold better mileage cars.
5. Task-5--- We found among Hyundai and Maruti, how many of them we can use legally in all states of India.

From this project, we learnt how Indian choices of car changed with time, how car companies growed from 1983 to 2020, some major incidents that changed the trajectory of path of development of cars and some most popular Car Companies.

## **FUTURE GOAL**
---

We will try to add more varieties of vehicle in the future like bikes,trucks,speedboats,planes,ships etc. We will try to help the user to have an option to give his requirement and show data from which he can choose his/her vehicle. We will try to add more interesting questions and ideas in the future.

# **LINKS**
---
1. https://www.kaggle.com/datasets?fileType=csv
2. https://jovian.ml/forum/t/recommended-datasets-for-course-project/11711
3. https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
4. https://auto.economictimes.indiatimes.com/news/industry/auto-expo-2016-popularised-hard-selling-diesel-cars-avoiding-health-risks-cse/50936818
5. https://www.google.co.in/
6. https://www.kaggle.com/nehalbirla/vehicle-dataset-from-cardekho?select=Car+details+v3.csv
"""